### ISSUE TITLE
engine should not be enabled by default

### ISSUE THREAD

**Issue by Fohlen** [apollographql/graphql-server-example#7]
```js
    engine: {
      apiKey: process.env.ENGINE_API_KEY
    }
```

Will cause the server to fail at startup with 
```js
           throw new Error('To use EngineReportingAgent, you must specify an API key via the apiKey option or the ENGINE_API_KEY environment variable.');
            ^

Error: To use EngineReportingAgent, you must specify an API key via the apiKey option or the ENGINE_API_KEY environment variable.
    at new EngineReportingAgent (/Users/berger/workspace/graphql-server-example/node_modules/apollo-engine-reporting/dist/agent.js:41:19)
    at new ApolloServerBase (/Users/berger/workspace/graphql-server-example/node_modules/apollo-server-core/dist/ApolloServer.js:117:41)
    at new ApolloServer (/Users/berger/workspace/graphql-server-example/node_modules/apollo-server-express/dist/ApolloServer.js:41:1)
    at new ApolloServer (/Users/berger/workspace/graphql-server-example/node_modules/apollo-server/dist/index.js:20:9)
    at Object.<anonymous> (/Users/berger/workspace/graphql-server-example/index.js:46:18)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```
as an error message. That's quite a pity for beginners. I recommend to remove or comment out this behaviour from the default configuration.

**Comment by JakeDawkins** [comment]
@Fohlen true! I guess the confusion is that this project is also used for the [deployment guides](https://www.apollographql.com/docs/apollo-server/deployment/now.html#env-variables) in the docs (where it says the key is required). I'll open a PR really quickly to fix that
